# Generated by Django 3.2.5 on 2021-08-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_book', '0003_song_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
