# Generated by Django 3.2.5 on 2021-08-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_book', '0004_song_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='video',
            field=models.TextField(default='Video goes here'),
        ),
    ]
