# Generated by Django 3.2.5 on 2021-08-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_book', '0005_alter_song_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='video',
            field=models.TextField(default='https://www.youtube.com/embed/NpEaa2P7qZI'),
        ),
    ]
