# Generated by Django 3.2.5 on 2021-08-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_book', '0007_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='file',
            field=models.FileField(upload_to='recordings/'),
        ),
    ]
