# Generated by Django 3.2.5 on 2021-08-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_book', '0008_alter_recording_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='file',
            field=models.FileField(upload_to='song_book/recordings/'),
        ),
    ]
