# Generated by Django 3.2.5 on 2021-08-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_book', '0009_alter_recording_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='name',
            field=models.TextField(default=models.DateTimeField(auto_now_add=True)),
        ),
    ]
