# Generated by Django 3.2.5 on 2021-07-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goals',
            old_name='goal_text',
            new_name='text',
        ),
    ]
