# Generated by Django 3.2.5 on 2021-08-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='text',
            field=models.TextField(default='Placeholder'),
        ),
    ]
