# Generated by Django 3.2.5 on 2021-08-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_goal_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='date_str',
            field=models.TextField(default='<django.db.models.fields.DateField>'),
        ),
    ]
