# Generated by Django 3.2.5 on 2021-08-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_goal_date_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date_str',
            field=models.TextField(blank=True, null=True),
        ),
    ]
