# Generated by Django 3.2.5 on 2021-08-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='editing',
        ),
        migrations.AddField(
            model_name='task',
            name='colour',
            field=models.TextField(default=''),
        ),
    ]
